// Install GraphQL plugin (https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql) 
// The VSCode extension will pick up the graphql.config.js file and use 
// the autogenerated file from Gatsby’s .cache directory. 
// Giving you autocompletion like in GraphiQL in any of your queries.
module.exports = require('./.cache/typegen/graphql.config.json')
